// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ervikfqiwmhyxcsohied.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVydmlrZnFpd21oeXhjc29oaWVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NDk0NjAsImV4cCI6MjA2NzIyNTQ2MH0.l1I27MaiViy6C6xMOVrxphwm5ZAaPq8tEaSyUA9mRwE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});